### ISSUE TITLE
Use actual geometry instead of bbox

### ISSUE THREAD

**Issue by maning** [osmlab/osmlint-osmium#14]
The output of TR validators are bbox of the relation members, its difficult to find the actual relation when loaded to the editor especially when the bbox is big.  **Let's use the actual geometries of the relations instead.**

![screen shot 2018-03-14 at 09 26 54](https://user-images.githubusercontent.com/353700/37382691-1ce97b94-276a-11e8-8eca-67060008d46a.png)

**Comment by Rub21** [comment]
@maning , it should contain the TR members too 🤔 , I've added that functionality..

**Comment by maning** [comment]
Thanks!
