### ISSUE TITLE
Validator for our team edits

### ISSUE THREAD

**Issue by dannykath** [osmlab/osmlint-osmium#9]
@Rub21 
I would like to check editions of our team , because when I was working on TR in NYC I found a  edition of he team currently are working on TR in some cities using OSM Navigation Map and JOSM.

http://osmhistory.appspot.com/relation/7574343/1
![1](https://user-images.githubusercontent.com/8483644/30554783-350fd64c-9c95-11e7-931f-f7f97a00e68a.png)

http://osmhistory.appspot.com/relation/7574343/2
![2](https://user-images.githubusercontent.com/8483644/30554799-420bed68-9c95-11e7-97d7-7103a559a611.png)

[Mapillary](https://www.mapillary.com/app/?lat=40.704953055555535&lng=-74.00761638888889&z=19&pKey=AaU-IIgl8d_4qHxOqcNVIg&focus=photo&x=0.4909152963402661&y=0.4905197374722392&zoom=0)
![tr](https://user-images.githubusercontent.com/8483644/30555185-64869086-9c96-11e7-8b96-d8d1afa57485.png)

cc @maning

**Comment by Rub21** [comment]
@dannykath @maning, I think it is not necessary to get the editions, you could  run  the validators https://github.com/osmlab/osmlint-osmium/blob/master/doc.md and get the wrong issues, from the team or from other users community users.

**Comment by Rub21** [comment]
@dannykath   you could use  this https://github.com/osmlab/osmlint-osmium/blob/master/src/validators/filterTRByUsers/README.md
